// Build-time publish step for blog posts.
//
// Decides once, as of the build, which posts are live and writes only those to
// src/shared/data/published-posts.generated.ts. The site reads that module and
// nothing else, so an unpublished post (future `date`, or `draft: true`) never
// reaches browser JS, server bundles, pages or the sitemap.
//
// Cutoff is the UTC date of the build. BUILD_DATE=YYYY-MM-DD overrides it.
//
// Local preview, `--dev` only (the predev script passes it):
//   SHOW_SCHEDULED=1  also include future-dated posts
//   SHOW_DRAFTS=1     additionally include `draft: true` posts
// Both are ignored without `--dev`, and when NODE_ENV or VERCEL_ENV is
// "production" or CI / WORKERS_CI is set.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { allOfficeBlogPosts } from '../src/shared/data/office_blog_posts';

const OUT_PATH = join(import.meta.dirname, '..', 'src', 'shared', 'data', 'published-posts.generated.ts');

const dev = process.argv.includes('--dev');
const env = process.env;

const productionLike =
    env.NODE_ENV === 'production' ||
    env.VERCEL_ENV === 'production' ||
    Boolean(env.CI) ||
    Boolean(env.WORKERS_CI);

const requestedPreview = env.SHOW_SCHEDULED === '1' || env.SHOW_DRAFTS === '1';
const previewAllowed = dev && !productionLike;
if (requestedPreview && !previewAllowed) {
    console.log('SHOW_SCHEDULED / SHOW_DRAFTS ignored: only honoured with --dev outside production and CI.');
}
const showScheduled = previewAllowed && (env.SHOW_SCHEDULED === '1' || env.SHOW_DRAFTS === '1');
const showDrafts = previewAllowed && env.SHOW_DRAFTS === '1';

if (env.BUILD_DATE && productionLike) {
    console.log('BUILD_DATE ignored: only honoured for local builds outside production and CI.');
}
const buildDate = (!productionLike && env.BUILD_DATE) || new Date().toISOString().slice(0, 10);
if (!/^\d{4}-\d{2}-\d{2}$/.test(buildDate)) {
    throw new Error(`BUILD_DATE must be YYYY-MM-DD, got "${buildDate}"`);
}

const published = allOfficeBlogPosts.filter((post) => {
    if (post.draft && !showDrafts) return false;
    return showScheduled || post.date <= buildDate;
});

const header = [
    '// GENERATED by scripts/generate-published-posts.ts. Do not edit; not tracked in git.',
    '// Contains only the posts published as of the build.',
    '',
    'import type { BlogPost } from "./blog-post-type";',
    '',
].join('\n');

const body = `export const publishedPosts: BlogPost[] = ${JSON.stringify(published, null, 4)};\n`;
writeFileSync(OUT_PATH, `${header}\n${body}`, 'utf8');

console.log(
    `published-posts: ${published.length} published, ${allOfficeBlogPosts.length - published.length} held back, cutoff ${buildDate}` +
        (showScheduled ? ' (preview: scheduled included)' : '') +
        (showDrafts ? ' (preview: drafts included)' : ''),
);
